options {
    directory "/var/cache/bind";
    recursion no;
    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { none; };
};

zone "victima.local" {
    type master;
    file "/etc/bind/victima.local.zone";
};