options {
    directory "/var/cache/bind";
    recursion yes;
    allow-recursion { any; };
    forwarders {};
    dnssec-validation no;
    listen-on { any; };
    listen-on-v6 { none; };
};

zone "victima.local" {
    type forward;
    forwarders { 192.168.150.20; };
};